name: Generate Snake
on:
  push:
    branches:
      - master

jobs:
  push_to_master:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Updated to use the latest version

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Make changes (example)
        run: |
          # Make some changes here
          echo "Some changes" >> file.txt
          git add .
          git commit -m "Made some changes"

      - name: Push changes
        env:
          ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
        run: |
          git push https://$ACTIONS_PAT@github.com/mdyhakash/mdyhakash.git HEAD:master
