name: Generate Snake

on:
  schedule: # Run workflow automatically
    - cron: "0 0 * * *"  # Every day at midnight
  workflow_dispatch: # Allows for manual execution

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate snake animation
        uses: Platane/snk@v2
        with:
          github_user_name: mdyhakash
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Upload the result to the repository
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
